name: deploy binaries

on: [pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run cross compilation build
        run: |
          cargo build --release
          sudo rm ./releases/build_tools_x86_64_unknown_linux_musl
          cp ./target/release/build_tools ./releases/build_tools_x86_64_unknown_linux_musl
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
                # ./releases/build_tools_aarch64_apple_darwin
                # ./releases/build_tools_x86_64_apple_darwin
                ./releases/build_tools_x86_64_unknown_linux_musl
            commit-msg: Update resources
            github-token: ${{ secrets.ACCESS_TOKEN }}