name: deploy binaries

on: [pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run cross compilation build
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
          cargo install cross --git https://github.com/cross-rs/cross
          git clone https://github.com/cross-rs/cross
          git submodule update --init --remote
          cd cross
          cd ..
          rm -rf cross
          cross build --target x86_64-unknown-linux-musl --release
          cross build --target aarch64-apple-darwin --release
          cross build --target x86_64-apple-darwin --release
          rm -r releases
          mkdir releases

          cp ./target/aarch64-apple-darwin/release/build_tools ./releases/build_tools_aarch64_apple_darwin
          cp ./target/x86_64-unknown-linux-musl/release/build_tools ./releases/build_tools_x86_64_unknown_linux_musl
          cp ./target/x86_64-apple-darwin/release/build_tools ./releases/build_tools_x86_64_apple_darwin
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
                ./releases/build_tools_aarch64_apple_darwin
                ./releases/build_tools_x86_64_apple_darwin
                ./releases/build_tools_x86_64_unknown_linux_musl
            commit-msg: Update resources
            github-token: ${{ secrets.ACCESS_TOKEN }}